[package]
name = "iori"
version = "0.1.0"
edition = "2021"

[dependencies]
async-recursion = "1.0.5"
futures-util = "0.3.30"
log = "0.4.20"
m3u8-rs = "5.0.5"
reqwest = { version = "0.11.24", features = ["stream"] }
tokio = { version = "1.36.0", features = ["full"] }
