[workspace]
members = ["bin/*", "crates/*"]

[workspace.dependencies]
iori = { path = "crates/iori" }
regex = "1.9.3"
tokio = { version = "1" }

fake_user_agent = "0.2.1"
anyhow = "1.0.81"
log = "0.4.20"

serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.102"

reqwest = { version = "0.11.24", default-features = false, features = [
    "rustls",
    "stream",
] }
