[package]
name = "iori"
version = "0.1.0"
edition = "2021"

[dependencies]
async-recursion = "1.0.5"
futures-util = { version = "0.3.30", features = ["io"] }
log = "0.4.20"
m3u8-rs = "5.0.5"
reqwest = { version = "0.11.24", default-features = false, features = [
    "rustls",
    "stream",
] }
tokio = { version = "1.36.0", features = ["full"] }

aes = "0.8.2"
cbc = { version = "0.1.2", features = ["std"] }
block-buffer = "0.10.4"
data-url = "0.3.1"
hex = "0.4.3"
mp4decrypt = "0.4.2"
tempfile = "3.10.0"
rand = "0.8.5"
thiserror = "1.0.57"
url = "2.5.0"

[dev-dependencies]
anyhow = "1"
pretty_env_logger = "0.5.0"
