[workspace]
members = ["bin/*", "crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["Yesterday17 <mmf@mmf.moe>"]
repository = "https://github.com/Yesterday17/iori"
license = "Apache-2.0"

[workspace.dependencies]
iori = { path = "crates/iori" }
iori-nicolive = { path = "crates/nicolive" }

regex = "1.9.3"
tokio = { version = "1", features = ["signal", "process"] }

fake_user_agent = "0.2.1"
anyhow = "1.0.81"
log = "0.4.20"

serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.102"

reqwest = { version = "0.12", default-features = false, features = [
    "rustls-tls",
    "stream",
] }
