[package]
name = "shiori"
description = "A brand new m3u8 stream downloader"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
iori.workspace = true
iori-nicolive.workspace = true
iori-showroom.workspace = true

tokio = { workspace = true, features = ["full"] }
reqwest.workspace = true
fake_user_agent.workspace = true
anyhow.workspace = true
log.workspace = true
serde.workspace = true

clap = { version = "4.4.18", features = ["derive", "env"] }
clap-handler = { version = "0.1.1", features = ["async"] }
rand = "0.9.0"
regex.workspace = true
async-recursion.workspace = true
shlex = "1.3.0"
rmp-serde = "1.3.0"
base64.workspace = true
chrono = "0.4.39"
ratatui = "0.29.0"
crossterm = "0.28.1"

[[bin]]
name = "shi"
path = "src/main.rs"
