[package]
name = "iori-minyami"
version = "0.1.0"
edition.workspace = true

[dependencies]
iori.workspace = true
iori-nicolive.workspace = true

tokio = { workspace = true, features = ["full"] }
reqwest.workspace = true
fake_user_agent.workspace = true
anyhow.workspace = true
log.workspace = true

clap = { version = "4.4.18", features = ["derive", "env"] }
pretty_env_logger = "0.5.0"

[[bin]]
name = "minyami"
path = "src/main.rs"
