[package]
name = "iori-minyami"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["full"] }
iori.workspace = true
reqwest.workspace = true
fake_user_agent.workspace = true
anyhow.workspace = true
log.workspace = true

clap = { version = "4.4.18", features = ["derive", "env"] }
pretty_env_logger = "0.5.0"
