[package]
name = "ssadecrypt"
version = "0.1.1"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
iori-ssa.workspace = true
clap.workspace = true
hex = "0.4.3"
